version: "3.1"
services:
    db:
        image: mysql
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: Aevraul
            MYSQL_PASSWORD: luar
            MYSQL_ROOT_PASSWORD: luar 
        volumes:
            - ./db:/docker-entrypoint-initdb.d
        networks:
            - default
    www:
        build: .
        ports: 
            - "80:80"
        volumes:
            - ./www:/var/www/html
        links:
            - db
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: luar
            MYSQL_ROOT_PASSWORD: luar 
volumes:
    persistent: