export const gameOne = {
  levelOne: {
    adjectives: [
      'loud', 
      'husky', 
      'harsh', 
      'faint', 
      'wide', 
      'tall'
    ],
  },
  levelTwo: {
    adjectives: [
      'large',
      'fat',
      'big',
      'thin',
      'straight',
      'steep',
      'square',
      'jagged',
      'flat',
      'deep',
      'crooked',
      'quiet',
    ],
  },
  levelThree: {
    adjectivesOne: [
      'crooked',
      'quiet',
      'raspy',
      'shrill',
      'silent',
      'whispering',
      'quick',
      'slow',
      'swift',
      'juicy',
      'curly',
      'dusty',
      'filthy',
      'flaky',
      'bland',
      'different',
    ],
    adjectivesTwo: [
      'fresh',
      'greasy',
      'hot',
      'salty',
      'stale',
      'tasty',
      'ancient',
      'brief',
      'early',
      'late',
      'long',
      'new',
      'old',
      'quick',
      'short',
      'young',
    ],
    adjectivesThree: [
      'difficult',
      'easy',
      'fake',
      'guilty',
      'infamous',
      'innocent ',
      'open',
      'nervous',
      'obnoxious',
      'pleasant',
      'outgoing',
      'outstanding',
      'puzzled',
      'real',
      'rich',
      'right',
    ],
  },
};

export let gameTwo = {
  levelOne: {
    adjectives: ['harsh', 'brainy', 'dusty', 'straight'],
  },
  levelTwo: {
    adjectives: [
      'square',
      'fat',
      'sleepy',
      'big',
      'cool',
      'dirty',
      'safe',
      'alive',
      'cold',
    ],
  },
  levelThree: {
    adjectivesOne: [
      'clever',
      'hot',
      'successful',
      'fake',
      'raspy',
      'ancient',
      'swift',
      'lucky',
      'envious',
      'broken',
      'eerie',
      'dead',
      'confused',
      'amused',
      'plain',
      'super',
    ],
    adjectivesTwo: [
      'lovely',
      'stormy',
      'healthy',
      'arrogant',
      'distinct',
      'sparkling',
      'blushing',
      'good',
      'exuberant',
      'cute',
      'kind',
      'jolly',
      'elegant',
      'dirty',
      'sleepy',
      'broken',
    ],
    adjectivesThree: [
      'gleaming',
      'wrong',
      'foolish',
      'fancy',
      'crowded',
      'weak',
      'condemned',
      'hungry',
      'relieved',
      'dangerous',
      'right',
      'steep',
      'crazy',
      'open',
      'slippery',
      'raspy',
    ],
  },
};



export const gameThree = {
  adjectives: [
    "relieved",
    "envious",
    "successful",
    "cool",
    "amused",
    "wrong",
    "eerie",
    "lucky",
    "broken",
    "healthy",
    "cold",
    "harsh",
    "raspy",
    "sparkling",
    "exuberant",
    "condemned",
    "slippery",
    "alive",
    "hungry",
    "kind",
    "distinct",
    "weak",
    "right",
    "dangerous",
    "lovely",
    "crowded",
    "cute",
    "blushing",
    "dead",
    "broken"
  ]
}
