FROM nginx
RUN mv /usr/share/nginx/html/index.html /usr/share/nginx/html/initial.html 
COPY ./index.html /usr/share/nginx/html/ 
RUN echo "Bie nvenidos al contenedor de raul (pitufo)"
EXPOSE 80/udp
# MOVE /usr/share/nginx/html/index.html /usr/share/nginx/html/initial.html
